name: Run Python Script with API Key

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          API_KEY: ${{ secrets.GEMINI_API }}  # Map the GitHub secret to API_KEY
        run: python your_script.py

      - name: Debug Environment Variables
         env:
           API_KEY: ${{ secrets.GEMINI_API }}
         run: |
           echo "API_KEY is set to: $API_KEY"
