jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        - name: Run script
        env:
          API_KEY ${{ secrets.API_KEY }}
        run: |
          python inputAnalysis.py
